### ISSUE TITLE
how to start?

### ISSUE THREAD

**Issue by adrian-rt** [portantier/vulpy#4]
Hi,

I set
 FLASK_APP=vulpy
FLASK_ENV=development

and when I do flask run, it throws an error "can't import module vulpy".

thanks.

**Comment by Barkhat26** [comment]
Launch the application via a script `vulpy.py` (`python bad/vulpy.py` or `python good/vulpy.py` )

**Comment by Barkhat26** [comment]
Why did you close this issue if you don't publish launching instructions (e.g. in README)?
